version: '3'
services:
  gem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/gem
      - gem_cache:/usr/local/bundle
    command: bash

volumes:
  gem_cache:
    driver: local
